### ISSUE TITLE
Bug: Image embed fills search bar with directory when image doesn't exist

### ISSUE THREAD

**Issue by 055110** [geteso/eso#28] opened 2023-06-07 14:28 UTC
Steps to reproduce:
1. Make a conversation and embed an image in a directory "7BZ1" (for this example)
2. Refresh the page.
3. Search bar gets filled by an unknown force.

**Comment by aokod** [comment] 2023-07-26 01:58
I am unable to reproduce this bug, but I do have a few questions:

1. By "embed an image in a directory", I assume you are referring to the URL of the image? (For example: `<img src='ZBZ1'>` or `<img src='https://example.com/ZBZ1(.jpg)'>`)  Or are you referring to a directory within the forum itself, such as `myforum.com/ZBZ1.jpg`?
2. What operating system and web server are you hosting your forum with?
3. Finally, what appears in the search bar when you refresh the page?

Thanks!

**Comment by 055110** [comment] 2023-08-03 13:45
> I am unable to reproduce this bug, but I do have a few questions:
> 
> 1. By "embed an image in a directory", I assume you are referring to the URL of the image? (For example: `<img src='ZBZ1'>` or `<img src='https://example.com/ZBZ1(.jpg)'>`)  Or are you referring to a directory within the forum itself, such as `myforum.com/ZBZ1.jpg`?
> 2. What operating system and web server are you hosting your forum with?
> 3. Finally, what appears in the search bar when you refresh the page?
> 
> Thanks!

Hello and apologies for late response.

1. Yes, it was `<img src='http://myforum.com/ZBZ1/'>`
2. I was using InfinityFree Web Hosting services, Linux and Apache I think.
3. The directory name fills the searchbar (ZBZ1)

**Comment by aokod** [comment] 2024-01-15 18:42
Thanks for providing me with some context regarding this issue.  I have attempted to reproduce the bug under the same conditions (Ubuntu 22--don't know which distribution you are using--and Apache) but alas, I am unable to get the same result.  
In order to let me troubleshoot the issue, you may provide the error log specified in your web server configuration, and if nothing is present, you may supply the access log.  Otherwise, I am going to close this issue seeing as we have been unable to reproduce the bug and so it is likely that **this is indicative of a greater problem** with your web server installation.

**Closed as completed by aokod** 2024-01-15 18:42 UTC
